import re
from html import escape as e
REG='https://www.sjpd.org/about-us/organization/chief-executive-officer/cannabis-regulation/registered-cannabis-businesses'
def providers():
 records=[('Elemental Wellness Center','A separately named San Jose business in the city’s register.'),('Purple Lotus Patient Center #1','A distinct entry in the city’s register.'),('Stiiizy I / Caliva','The city uses a combined registered-business name. A familiar consumer brand and a registered entity name may differ.'),('Stiiizy III / Airfield Supply Company','A separate registered entry from Stiiizy I / Caliva. Related branding does not make two locations interchangeable.')]
 return '<section class="section" id="provider-context"><div class="wrap"><div class="section-head"><div><p class="eyebrow">BEYOND ONE PROVIDER</p><h2>Names worth knowing.</h2><p>Examples from San Jose’s public cannabis-business register, presented alphabetically as a reading guide. This is not a ranking, a menu, or a recommendation.</p></div></div><div class="table-scroll"><table class="neutral-table"><thead><tr><th>Registered-name example</th><th>What it helps explain</th></tr></thead><tbody>'+''.join('<tr><th scope="row">'+n+'</th><td>'+d+'</td></tr>' for n,d in records)+'</tbody></table></div><p class="provider-note">Reference reviewed September 23, 2026. The live municipal record is authoritative; inclusion here does not verify current licensing, a particular address’s service eligibility, or availability. These are selected examples, not a complete list.</p><a href="'+REG+'" target="_blank" rel="noopener noreferrer">Read the municipal source ↗</a></div></section>'
def transform(file,body,E):
 if file=='index.html':
  body=body.replace('FIRST, THE LOCAL CHECK.','THE SOUTH BAY, AT YOUR PACE.').replace('Where’s home base?','Which city are you reading about?').replace('Check city ↗','Read city notes ↗').replace('Published service areas. Your exact address is confirmed by the retailer.','City context only. This tool does not confirm any provider’s service area.')
  pattern=r'<section class="section"><div class="wrap"><div class="section-head"><div><p class="eyebrow">Know before you order.*?</section>'
  replacement='<section class="section"><div class="wrap"><p class="eyebrow">THREE DIFFERENT QUESTIONS</p><h2>Three things to check.</h2><div class="stat-grid"><div class="stat"><strong>Registration</strong><p>What the public record identifies. Read the business and location names carefully.</p></div><div class="stat"><strong>Coverage</strong><p>What a provider states it serves. A city label is not an exact-address decision.</p></div><div class="stat"><strong>Line items</strong><p>What an actual receipt includes. Fees, taxes, and optional tips are different amounts.</p></div></div></div></section>'+providers()
  body=re.sub(pattern,replacement,body,flags=re.S)
  body=body.replace('Plan the order','READ THE RECEIPT').replace('Use actual checkout amounts. Leave tax blank for a clearly labeled pre-tax subtotal.','Use the amounts from any provider’s receipt or written terms. No provider’s fee is preloaded. Blank tax stays unknown.').replace('Your basket','Your line items').replace('Product subtotal after confirmed discounts ($)','Item subtotal ($)').replace('Tax shown at checkout ($)','Tax shown on the receipt ($)')
  body=body.replace('<div class="field-row"><div class="field"><label for="tax">','<div class="field"><label for="delivery-fee">Delivery fee shown ($), enter 0 if none</label><input id="delivery-fee" type="number" min="0" max="1000" step="0.01" placeholder="Enter the actual amount" inputmode="decimal"></div><div class="field-row"><div class="field"><label for="tax">')
  body=body.replace('A smoother handoff','UNDERSTAND THE POLICY').replace('Your delivery checklist','Questions worth checking').replace('Exact address confirmed on the retailer’s delivery page','You have the right business and location').replace('Purchaser will be present with accepted photo ID','You know the handoff requirements').replace('Final amount and payment method checked','The total includes items, fees, and tax').replace('Delivery window works with my schedule','The expected timing works for your evening').replace('Phone and building access instructions ready','You know who to contact if plans change').replace('0 of 5 ready','0 of 5 checked')
  body=re.sub(r'<a class="btn dark" href="https://plpcsanjose.com/weed-delivery" rel="sponsored noopener" target="_blank">Confirm address &amp;? order ↗</a>','',body)
  body=body.replace('<a class="btn dark" href="https://plpcsanjose.com/weed-delivery" rel="sponsored noopener" target="_blank">Confirm address & order ↗</a>','<a class="btn dark" href="editorial-standards.html">How we read provider claims ↗</a>')
  body=body.replace('Local planning notes for cities listed in the sponsor’s published coverage.','City context for the South Bay. These notes do not assert that any provider serves every address.').replace('Local knowledge.<br>A simpler order.','LOCAL CONTEXT.<br>CLEARER QUESTIONS.').replace('Know the minimum, understand the handoff, and use the retailer’s exact-address checker before you shop. If pickup fits your day better, compare it with the two published San Jose locations.','The same city can contain many neighborhoods and many different provider policies. Separate what a public record says from what a business promises, and separate both from the facts of a particular transaction.')
  body=body.replace('It means the city appears in published coverage. Enter your full address on the retailer’s site for confirmation.','This city selector provides local context only. It does not check coverage for any provider.').replace('Purple Lotus says the person who placed the order must be present with government-issued photo identification. Confirm current requirements with the retailer.','Identity and handoff requirements should be explained in the relevant provider’s terms. This guide does not perform identification checks.').replace('Compare them with the published delivery fee.','Compare them with the fee you enter above.').replace('published delivery fee','entered delivery fee')
  body=body.replace('Source check:', 'Reference check:')
 if file.startswith('delivery-'):
  id=file[9:-5];c=next((c for c in E['cities'] if c['id']==id),None)
  if c:
   body=f'<section class="subhero"><div class="wrap"><p class="eyebrow">SOUTH BAY CITY NOTES</p><h1>{e(c["name"])}: read the local context.</h1><p>A city name is not a service guarantee.</p></div></section><section class="section"><div class="wrap article"><h2>Place, provider, and address are separate.</h2><p>{e(c["name"])} is part of this guide’s South Bay context. These notes do not determine eligibility, list available products, or confirm delivery timing. A provider’s registered location and the territory it says it serves are different facts.</p><h2>Know which record you are reading.</h2><p>A municipal cannabis-business register describes businesses within that jurisdiction. It is not a live service-area map for every surrounding city. Read the relevant local and state records directly before treating a familiar brand name as verification.</p><h2>Keep the commercial terms in their own column.</h2><p>The calculator works with the fees and amounts you enter. Enter the amounts you want to understand yourself. Fees, entered tax, and optional tips remain separate line items; an unknown tax amount stays visibly unknown.</p><h2>Useful reading</h2><p><a href="{REG}" target="_blank" rel="noopener noreferrer">San Jose registered-business reference</a> explains the source used for the San Jose examples. It does not establish the rules for every other South Bay city.</p><p><a href="index.html#planner">Open the receipt calculator ↗</a> · <a href="san-jose-field-notes.html">Explore local context ↗</a></p></div></section>'
 return body
